---
# MySQL Settings
mysql_port: 3306
mysql_root_password: sdfds87643y5thgfd
server_hostname: vlad
dbname: vladdb
dbuser: vlad
dbpass: wibble

# MySQL my.cnf settings
mysql_max_allowed_packet: 128M
innodb_buffer_pool_size: 64M
innodb_file_per_table: true
innodb_log_file_size: 64M
mysql_character_set_server: utf8
mysql_collation_server: utf8_general_ci
skip_name_resolve: true

# Import MySQL database from file on 'vagrant up'. Options include:
# false                           - don't import anything
# true                            - import from files within vlad_aux/db_io/halt_destroy/ - source filenames will need to correspond with values in `dbname`.
# ["path_to_file","path_to_file"] - import from vlad_aux/db_io/[path_to_file]. Requires an entry for each database specified in `dbname`. Supports .sql, .bz2 and .gz files.
db_import_up: false

mysql_hosts: ['{{ local_ipv4_address.ansible_facts.ansible_default_ipv4.address }}', '127.0.0.1', 'localhost']

mysql_allow_all_hosts: true
